<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\operators;

class OperatorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $operators = [
            'Algeria Djezzy',
            'Algeria Mobilis',
            'Algeria Ooredoo',
            'Angola Africell',
            'Angola Movicel',
            'Angola Unitel',
            'Mali Orange',
            'Botswana Btc Mobile',
            'Botswana Mascom',
            'Botswana Orange',
            'Burkina Faso Moov',
            'Burkina Faso Orange',
            'Burkina Faso Telecel',
            'Burundi Econet Leo',
            'Burundi Lacell',
            'Burundi Lumitel',
            'Burundi Onamob',
            'Cameroon Camtel',
            'Cameroon Mtn',
            'Cameroon Nextel',
            'Cameroon Orange',
            'Cape Verde CVMovel',
            'Cape Verde Unitel T+',
            'Central African Rep. Moov',
            'Central African Rep. NationLink',
            'Central African Rep. Orange',
            'Central African Rep. Telecel',
            'Chad Airtel',
            'Chad Moov Africa',
            'Comores Telecom',
            'Comores Telco',
            'CIV Moov',
            'CIV Mtn',
            'CIV Orange',
            'Congo DR Africell',
            'Congo DR Airtel',
            'Congo DR Orange',
            'Congo DR Vodacom',
            'Djibouti Evatis',
            'Egypt Etisalat',
            'Egypt Orange',
            'Egypt TE',
            'Egypt Vodafone',
            'Equa. Guinea Hits-GE',
            'Equa. Guinea Orange',
            'Eritrea EriTel',
            'Eswatini SPTC',
            'Eswatini Swazi Mobile',
            'Eswatini Mtn',
            'Ethiopia Ethio Telecom',
            'Ethiopia Safaricom',
            'Gabon Airtel',
            'Gabon Libertis',
            'Gabon Moov',
            'Gambia Africell',
            'Gambia Comium',
            'Gambia Gamcel',
            'Gambia QCell',
            'Ghana AirtelTigo',
            'Ghana Expresso',
            'Ghana Mtn',
            'Ghana Glo',
            'Ghana Vodafone',
            'Guinea-Bissau Guinetel',
            'Guinea-Bissau Orange',
            'Guinea-Bissau Spacetel',
            'Guinea Mtn',
            'Guinea Cellcom',
            'Guinea Intercel',
            'Guinea Orange',
            'Guinea SotelGui',
            'Kenya Airtel',
            'Kenya Safaricom',
            'Liban',
            'Kenya Telkom',
            'Lesotho Econet',
            'Lesotho Vodacom',
            'Lesotho Telecom',
            'Liberia LTC Mobile',
            'Liberia Mtn',
            'Liberia Orange',
            'Libya Al-Madar',
            'Libya LTT',
            'Libya Libyana',
            'Madagascar Airtel',
            'Madagascar Bip',
            'Madagascar Orange',
            'Madagascar Telma',
            'Malawi Airtel',
            'Malawi Telekom',
            'Mali Malitel',
            'Mali Telecel',
            'Mauritania Chinguitel',
            'Mauritania Mattel',
            'Mauritania Mauritel',
            'Mauritius Cellplus',
            'Mauritius Emtel',
            'Mauritius MTML',
            'Morocco Inwi',
            'Morocco Maroc Telecom',
            'Morocco Orange',
            'Mozambique Mcell',
            'Mozambique Movitel',
            'Mozambique Vodacom',
            'Namibia MTC',
            'Namibia Mtn',
            'Namibia Telecom',
            'Namibia TN Mobile',
            'Niger Sahelcom',
            'Niger Orange',
            'Nigeria Airtel',
            'Niger Airtel',
            'Nigeria 9Mobile',
            'Nigeria Glo',
            'Congo Airtel',
            'Congo Azur',
            'Congo Mtn',
            'Rwanda Airtel-Tigo',
            'Rwanda Mtn',
            'Sao Tome and Principe CSTmovel',
            'Sao Tome and Principe Unitel',
            'Senegal Expresso',
            'Senegal Free',
            'Senegal Orange',
            'Seychelles Airtel',
            'Seychelles CWS',
            'Seychelles Intelvision',
            'Sierra Leone Africell',
            'Sierra Leone Orange',
            'Sierra Leone Qcell',
            'Sierra Leone Sierratel',
            'Somalia AirSom',
            'Somalia Amtel',
            'Somalia Golis Telecom',
            'Somalia Hormuud',
            'Somalia Nationlink',
            'Niger Moov Africa',
            'NCell',
            'Somalia SomLink',
            'Somalia SomNet',
            'Somalia Somtel',
            'Somalia STG',
            'Somalia Telesom',
            'South Africa CELL C',
            'South Africa Mtn',
            'South Africa Telkom',
            'South Africa Vodacom',
            'South Sudan Digitel',
            'South Sudan Gemtel',
            'South Sudan Mtn',
            'South Sudan Vivacel',
            'South Sudan Zain',
            'Sudan Mtn',
            'Sudan Vivacel',
            'Sudan Zain',
            'Tanzania Airtel',
            'Tanzania Smart',
            'Tanzania Smile',
            'Tanzania TTCL Mobile',
            'Tanzania Tigo',
            'Tanzania Viettel',
            'Tanzania Vodacom',
            'Tanzania Zantel',
            'Togo Moov',
            'Togo Togocel',
            'Tunisia Ooredoo',
            'Tunisia Orange',
            'Tunisia Telecom',
            'Uganda Airtel',
            'Uganda Hamilton Telecom',
            'Uganda Mtn',
            'Uganda Smile',
            'Uganda Lycamobile',
            'Uganda UTL',
            'Zambia Airtel',
            'Zambia Beeline Telecoms',
            'Zambia Mtn',
            'Zambia Zamtel',
            'Zimbabwe Econet',
            'Zimbabwe NetOne',
            'Zimbabwe Telecel',
            'Benin Mtn',
            'Benin Sbin',
            'Nigeria Mtn',
            'Benin Moov'
        ];

        foreach ($operators as $name) {
            operators::create(['name' => $name]);
    }
}
}